export const COMPANIES_DATABASE = [
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000001',
        country: 'Bulgaria',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'BG',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000002',
        country: 'Bulgaria',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'BG',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000003',
        country: 'United States',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'US',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000004',
        country: 'Bulgaria',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'BG',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000005',
        country: 'France',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'FR',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000006',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000007',
        country: 'United States',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'US',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000008',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000009',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000010',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000011',
        country: 'Bulgaria',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'BG',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000012',
        country: 'Bulgaria',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'BG',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000013',
        city: 'London',
        country: 'United Kingdom',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000014',
        country: 'Bulgaria',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'BG',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000015',
        country: 'France',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'FR',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000016',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000017',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000018',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000019',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000020',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
    {
        name: 'Lowis & Sons Insurance',
        signature: '1000000021',
        country: 'United Kingdom',
        city: 'London',
        incorporated: '20-10-2015',
        address: '297 Manchester Road, CHELMSFORD, CM99 8TN',
        isoAlpha2Code: 'GB',
        addressLocality: {
            name: 'addressLocality.name',
        },
        addressRegion: {
            name: 'addressRegion',
            abbreviatedName: 'abbriviatedRegionName',
        },
        postalCode: '1000',
        streetAddress: {
            line1: 'streetAddress1',
            line2: 'streetAddress2',
        },
        duns: '354235',
    },
];
